//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula6
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aluno()
        {
            this.aluno_curso = new HashSet<aluno_curso>();
            this.aluno_disciplina = new HashSet<aluno_disciplina>();
        }
    
        public string ra { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string cpf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno_curso> aluno_curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno_disciplina> aluno_disciplina { get; set; }
    }
}
