//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula6
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno_disciplina
    {
        public string ra_aluno { get; set; }
        public int id_disciplina { get; set; }
        public int ano { get; set; }
        public Nullable<decimal> nota_p1 { get; set; }
        public Nullable<decimal> nota_p2 { get; set; }
        public Nullable<decimal> nota_p3 { get; set; }
        public int id { get; set; }
    
        public virtual aluno aluno { get; set; }
        public virtual disciplina disciplina { get; set; }
    }
}
