//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjAula6
{
    using System;
    using System.Collections.Generic;
    
    public partial class disciplina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disciplina()
        {
            this.aluno_disciplina = new HashSet<aluno_disciplina>();
            this.curso_disciplina = new HashSet<curso_disciplina>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> num_sala { get; set; }
        public string horario_inicio { get; set; }
        public string horario_fim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluno_disciplina> aluno_disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso_disciplina> curso_disciplina { get; set; }
    }
}
